name: release
on:
  push:
    branches: [master]

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: tree-sitter-beancount
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          extra-files: |
            Cargo.toml

  publish_npm:
    name: Publish npm
    runs-on: ubuntu-latest
    needs: [release-please]
    if: needs.release-please.outputs.release_created
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
